# Generated by Django 3.2.8 on 2022-01-15 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('event_picture', models.FileField(blank=True, null=True, upload_to='uploads/events/')),
                ('event_discription', models.TextField(blank=True, null=True)),
                ('event_youtube_link_key', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_form_urls', models.CharField(blank=True, max_length=250, null=True)),
                ('Start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Internship_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(default=datetime.date.today)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_education', models.CharField(blank=True, max_length=300, null=True)),
                ('name_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('education_date_from', models.CharField(blank=True, max_length=100, null=True)),
                ('education_date_to', models.CharField(blank=True, max_length=100, null=True)),
                ('Organization', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('date_from', models.CharField(blank=True, max_length=100, null=True)),
                ('date_to', models.CharField(blank=True, max_length=100, null=True)),
                ('responsibilities', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=150, null=True)),
                ('resume', models.FileField(upload_to='uploads/Internship_Application_cv/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=500)),
                ('news_picture', models.FileField(blank=True, null=True, upload_to='uploads/events/')),
                ('news_discription', models.TextField(blank=True, null=True)),
                ('news_youtube_link_key', models.CharField(blank=True, max_length=100, null=True)),
                ('news_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('partner_name', models.CharField(max_length=500, null=True)),
                ('partner_image', models.ImageField(null=True, upload_to='uploads/partners/')),
                ('partner_url', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default=1, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Qutation_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('Product_name', models.CharField(blank=True, max_length=250, null=True)),
                ('fullname', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.TextField(default='')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('to_date', models.DateField(default=datetime.date.today)),
                ('tenders_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tenders_description', models.TextField(blank=True)),
                ('tenders_pdf', models.FileField(upload_to='uploads/tenders/')),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default=1, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_price', models.CharField(blank=True, max_length=300, null=True)),
                ('HSN_CODE', models.CharField(blank=True, max_length=300, null=True)),
                ('product_image', models.ImageField(null=True, upload_to='uploads/products/')),
                ('product_option_image_1', models.ImageField(blank=True, null=True, upload_to='uploads/products-Option-image/')),
                ('product_option_image_2', models.ImageField(blank=True, null=True, upload_to='uploads/products-Option-image/')),
                ('product_option_image_3', models.ImageField(blank=True, null=True, upload_to='uploads/products-Option-image/')),
                ('product_option_image_4', models.ImageField(blank=True, null=True, upload_to='uploads/products-Option-image/')),
                ('product_specification_boucher', models.FileField(blank=True, null=True, upload_to='uploads/products/specification')),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default='1', max_length=50)),
                ('gst', models.CharField(choices=[('0', 'N/A'), ('12', '12%'), ('18', '18%')], default='0', max_length=50)),
                ('discount_type', models.CharField(choices=[('0', 'N/A'), ('Rs', 'Flat Discount'), ('%', 'Percentage Discount')], default='0', max_length=50)),
                ('discount_amount_or_per', models.IntegerField(default=0)),
                ('product_description', models.TextField(null=True)),
                ('upload_date', models.DateField(auto_now=True, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
