# Generated by Django 3.2.8 on 2022-02-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_year',
            fields=[
                ('Event_year', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='Event_year',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.event_year'),
        ),
    ]
