# Generated by Django 3.2.8 on 2022-02-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220209_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_year',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default='1', max_length=50),
        ),
    ]
