# Generated by Django 3.2.8 on 2022-02-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
    ]
