# Generated by Django 3.2.8 on 2022-02-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst',
            field=models.IntegerField(choices=[('0', 'N/A'), ('12', '12%'), ('18', '18%')], default='0', max_length=50),
        ),
    ]
