# Generated by Django 3.2.8 on 2022-02-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220214_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gst',
            field=models.CharField(choices=[('0', 'N/A'), ('12', '12%'), ('18', '18%')], default='0', max_length=50),
        ),
    ]
