# Generated by Django 3.2.8 on 2022-02-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=500)),
                ('job_discription_pdf', models.FileField(upload_to='uploads/Latest_notification/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default='1', max_length=50)),
                ('upload_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
