# Generated by Django 3.2.8 on 2022-02-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_latest_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_notification',
            name='discription',
            field=models.TextField(),
        ),
    ]
