# Generated by Django 3.2.8 on 2022-02-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220216_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qutation_request',
        ),
    ]
