# Generated by Django 3.2.8 on 2022-02-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_qutation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='qutation_request',
            name='other_product_name1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='qutation_request',
            name='other_product_name2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='qutation_request',
            name='other_product_qty1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='qutation_request',
            name='other_product_qty2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
