# Generated by Django 3.2.8 on 2022-02-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220219_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=500, null=True)),
                ('video_youtube_link_key', models.CharField(blank=True, max_length=100, null=True)),
                ('video_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default='1', max_length=50)),
            ],
        ),
    ]
