# Generated by Django 3.2.8 on 2022-03-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_our_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_video',
            name='video_Thumbnail_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='our_video',
            name='video_youtube_link_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
