# Generated by Django 3.2.8 on 2022-08-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_product_specification_boucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenders',
            name='tenders_pdf',
            field=models.FileField(max_length=500, upload_to='uploads/tenders/'),
        ),
    ]
