# Generated by Django 3.2.8 on 2022-01-15 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(default='', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('landmark', models.TextField()),
                ('billing_fullname', models.CharField(blank=True, max_length=150, null=True)),
                ('billing_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('billing_email', models.CharField(blank=True, max_length=80, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=150, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=150, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_address1', models.TextField(blank=True, null=True)),
                ('billing_address2', models.TextField(blank=True, null=True)),
                ('billing_landmark', models.TextField(blank=True, null=True)),
                ('billing_gst_no', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default=1, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='', max_length=60)),
                ('sortname', models.CharField(default='', max_length=60)),
                ('phonecode', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('cart', models.CharField(blank=True, max_length=200, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Invoice_number', models.CharField(blank=True, max_length=200, null=True)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('amount_initiated', models.FloatField(blank=True, null=True)),
                ('Date_of_payment', models.DateTimeField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=200, null=True)),
                ('order_status', models.CharField(choices=[('1', 'not Packed'), ('2', 'packed'), ('3', 'ON The Way'), ('4', 'Delivered')], default='1', max_length=50)),
                ('Payment_status', models.CharField(choices=[('1', 'PENDING'), ('2', 'SUCCESS'), ('3', 'FAILED'), ('4', 'AMOUNT Tampered')], default='1', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('was_success', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.address')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('alternative_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(max_length=100)),
                ('auth_token', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default=1, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default='', max_length=60)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.country')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(blank=True, max_length=300, null=True)),
                ('Product_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('Total_gst_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('Total_price_without_gst', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('product_image', models.FileField(blank=True, null=True, upload_to='uploads/product_order/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('order_Id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_document', models.FileField(blank=True, null=True, upload_to='uploads/products-Invoice/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('order_Id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_amount', models.IntegerField(blank=True, null=True)),
                ('gst_with_product_QTY', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('payable_price_withGST', models.IntegerField(blank=True, null=True)),
                ('payable_price_withoutGST', models.IntegerField(blank=True, null=True)),
                ('quantity', models.CharField(default=1, max_length=100)),
                ('total_product_QTY', models.IntegerField(blank=True, null=True)),
                ('total_price_with_QTY', models.IntegerField(blank=True, null=True)),
                ('total_price_without_gst_QTY', models.IntegerField(blank=True, null=True)),
                ('total_gst_with_QTY', models.IntegerField(blank=True, null=True)),
                ('add_date', models.DateField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default=1, max_length=50)),
                ('order_status', models.CharField(choices=[('1', 'Pending'), ('2', 'Order Placed'), ('3', 'Invoice generated')], default=1, max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.product')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.country'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.state'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
