# Generated by Django 3.2.8 on 2022-01-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20220117_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='order_Id',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='order_Id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
