# Generated by Django 3.2.8 on 2022-01-17 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0005_auto_20220117_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_Id', models.TextField(primary_key=True, serialize=False)),
                ('cart', models.CharField(blank=True, max_length=200, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Invoice_number', models.CharField(blank=True, max_length=200, null=True)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('amount_initiated', models.FloatField(blank=True, null=True)),
                ('Date_of_payment', models.DateTimeField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=200, null=True)),
                ('order_status', models.CharField(choices=[('1', 'not Packed'), ('2', 'packed'), ('3', 'ON The Way'), ('4', 'Delivered')], default='1', max_length=50)),
                ('Payment_status', models.CharField(choices=[('1', 'PENDING'), ('2', 'SUCCESS'), ('3', 'FAILED'), ('4', 'AMOUNT Tampered')], default='1', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('was_success', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.address')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
