# Generated by Django 3.2.8 on 2022-02-07 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomManager',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, upload_to='uploads/room_manager')),
                ('phone_no', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=50)),
                ('room_discription', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('Booked_by_admin', models.BooleanField(default=False)),
                ('price', models.FloatField(default=1000.0)),
                ('no_of_days_advance', models.IntegerField()),
                ('start_date', models.DateField()),
                ('room_image', models.ImageField(default='0.jpeg', upload_to='uploads/room_photos')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_booking.roommanager')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image_discription', models.TextField(blank=True, null=True)),
                ('room_picture', models.ImageField(default='0.jpeg', upload_to='uploads/room_photos')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_booking.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Order',
            fields=[
                ('order_number', models.TextField(primary_key=True, serialize=False)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, default=3000, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('adult_no', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Success'), ('3', 'Failed')], default=1, max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room_booking.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('Invoice_number', models.CharField(blank=True, max_length=200, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_initiated', models.FloatField(blank=True, null=True)),
                ('Date_of_payment', models.DateTimeField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=200, null=True)),
                ('Payment_status', models.CharField(choices=[('1', 'Pending'), ('2', 'Success'), ('3', 'Failed')], default='1', max_length=50)),
                ('log', models.TextField(blank=True, null=True)),
                ('was_success', models.BooleanField(default=False)),
                ('invoice_document', models.FileField(blank=True, null=True, upload_to='uploads/Room-Invoice/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='room_booking.room_order')),
                ('room_no', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='room_booking.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book_By_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guest_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Guest_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('Guest_email', models.CharField(blank=True, max_length=80, null=True)),
                ('adult_no', models.CharField(blank=True, max_length=20, null=True)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('Total_price', models.FloatField(blank=True, default=3000, null=True)),
                ('Booked_by', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('1', 'Booked'), ('2', 'Not Book')], default='1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='room_booking.rooms')),
            ],
        ),
    ]
