# Generated by Django 3.2.8 on 2022-02-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_by_admin',
            name='Booking_remark',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='book_by_admin',
            name='cancelled_remark',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
