# Generated by Django 3.2.8 on 2022-04-30 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_by_admin',
            name='check_in',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='book_by_admin',
            name='check_out',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
