# Generated by Django 3.2.8 on 2022-04-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0002_auto_20220430_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_by_admin',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book_by_admin',
            name='check_out',
            field=models.DateField(),
        ),
    ]
