# Generated by Django 3.2.8 on 2021-11-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_title', models.CharField(max_length=100, null=True)),
                ('center_description', models.TextField(blank=True, null=True)),
                ('center_image', models.ImageField(null=True, upload_to='uploads/center/')),
                ('center_video_key', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default=1, max_length=50)),
            ],
        ),
    ]
