# Generated by Django 3.2.8 on 2021-11-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_title', models.CharField(max_length=100, null=True)),
                ('hub_description', models.TextField(blank=True, null=True)),
                ('hub_image', models.ImageField(null=True, upload_to='uploads/Hub/')),
                ('hub_video_key', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default=1, max_length=50)),
            ],
        ),
    ]
