# Generated by Django 3.2.8 on 2021-11-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0002_ourhub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourhub',
            name='hub_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/Hub/'),
        ),
        migrations.AlterField(
            model_name='ourhub',
            name='hub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourhub',
            name='hub_video_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
