# Generated by Django 3.2.8 on 2021-11-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0004_auto_20211117_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(blank=True, max_length=100, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='uploads/Services/')),
                ('service_video_key', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactive'), ('3', 'Delete')], default=1, max_length=50)),
            ],
        ),
    ]
