# Generated by Django 3.2.8 on 2021-11-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0005_ourservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='service_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
