# Generated by Django 3.2.8 on 2021-11-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0006_ourservice_service_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourhub',
            name='hub_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
