# Generated by Django 3.2.8 on 2022-01-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0007_ourhub_hub_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='service_poster',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/Services/poster'),
        ),
    ]
