# Generated by Django 3.2.8 on 2022-01-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0009_auto_20220121_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='service_use4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
