# Generated by Django 3.2.8 on 2022-01-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0010_ourservice_service_use4'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
