# Generated by Django 3.2.8 on 2022-01-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0011_ourservice_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Contact_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
