# Generated by Django 3.2.8 on 2022-01-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0012_service_contact_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_contact_request',
            name='service_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
