# Generated by Django 3.2.8 on 2022-03-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0013_service_contact_request_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='center_brochure',
            field=models.FileField(blank=True, null=True, upload_to='uploads/center/'),
        ),
    ]
