# Generated by Django 3.2.8 on 2022-05-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0014_center_center_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='meta_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
