# Generated by Django 3.2.8 on 2022-05-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0015_auto_20220517_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='meta_discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='meta_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
