# Generated by Django 3.2.8 on 2022-07-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0016_auto_20220527_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='image_alt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='image_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourhub',
            name='image_alt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourhub',
            name='image_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='image_alt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='image_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
