# Generated by Django 3.2.8 on 2022-08-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourCenter', '0017_auto_20220706_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservice',
            name='service_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/Services/pdf'),
        ),
    ]
